appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c34e00c3aeb3c07004633ae
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: tFxXdXZDhHkGJJSHOk6qEQO3Xu2rliXGn+tDYQkO7Cojs5uAuG/yEbpHqiLvTDZv1hQwXGITNrfdFrDGO6p7A0mVya5QGeCCti9NtQR6b9e2aSV3NcqbJFZbXFAkFrPf39+S8BikY1aua9hLPmSvTMhK61XCBIEJyOF+fby5kD44EPsXO7IkxfkRElX0qGuCrOxuVuIokZpmoCNUjQVGAv7zzG2rQdeMpqztE35B7Pw27XOUQQH9ZZitWiMqw90KdhG5vBGZCYRHKOKJSB/abxPYrywgl7LhspIfIa+twiubJiLfoa7tI2UlIz5aW9QgNDuj/te+RxQUQEg8E3LuP+dNHl+V7NDNbYCUwhlYgouVRmunJ+seu9idySYFyOot8Q78gtTGYqPGbv56DdpXk19kjbvXYBvk8EG1C8dBwg5Lpl3vmUZ1mzv0Uk4XDpRkjTU4MgqvQG49zbqW70AkvnIS0hF2h/OFLJbxhjTCgsVjZQylBRPu8LgxSd6bF4G4ooYmqp47mUa49PYjs1OjW0gI9bmSvJPQ+qi2l3LxTGbaQd1IdL7zlRMVop3d4KERM1YMM3jtzlzsK88vl9kLVT/mmpBxhO7bWI5PHE921e095XfmnUfn8EhHu5Uwjj+MlVyKNwapI37LEQteF7+5mkFA+C48a6zhpBKIK425jmo=}
